
class TradeExitReason:
  SL_HIT = "SL HIT"
  TRAIL_SL_HIT = "TRAIL SL HIT"
  TARGET_HIT = "TARGET HIT"
  SQUARE_OFF = "SQUARE OFF"
  SL_CANCELLED = "SL CANCELLED"
  TARGET_CANCELLED = "TARGET CANCELLED"
  EXPIRY_EXIT = "EXPIRY EXIT ON MOVEMENT"
  EXPIRY_TWO_PERCENT_PROFIT = "ExPIRY PROFIT ACHIEVED"
  MANUAL = "MANUAL"
  SMI_DEMA_CROSSED = "SMI_DEMA_CROSSED"
  ROLLING_EXPIRY = "ROLLING_EXPIRY"
  